# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32a3866a990f680863313ea16701dded92cfb5f6399465c89e26f661e400fa51d96e48ca5714f52f0d175fb6948ec6d91c60ff0c419143492403018a4f5fcfc7

test:
  secret_key_base: efd9561449a4bb926de55a17dd8e76acfb33f82dfb1ff510122c041ae87e446c72fb061d4d8fa9265ac4944abd113379c02915aaee99ea1b4bad3b6076a6dc7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
